spring:
  flyway:
    placeholders:
      admin.email: ${ADMIN_EMAIL}
      admin.password.hash: ${ADMIN_PASSWORD_HASH}

  application:
    name: subscription-reminder
  profiles:
    active: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8080