-- ---------------------------------------------------------------------
-- users : the user account itself -- credentials and display settings
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id                   BINARY(16)    NOT NULL COMMENT 'PK (UUID v7, generated by the app)',
    username             VARCHAR(50)   NOT NULL COMMENT 'Display name',
    email                VARCHAR(255)  NOT NULL COMMENT 'Login identifier; also doubles as the notification address',
    password_hash        VARCHAR(255)  NOT NULL COMMENT 'BCrypt hash; plaintext is never stored',
    preferred_currency   VARCHAR(3)    NOT NULL COMMENT 'Display currency (ISO 4217). Default (CAD) is applied by the app',
    reminder_days_before INT           NOT NULL COMMENT 'How many days before the due date to notify. Default (3) is applied by the app',
    role                 VARCHAR(20)   NOT NULL COMMENT 'USER or ADMIN. Changed only via direct DB operation, never through the API',
    created_at           DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Created at (DB-controlled; the app never sets this column)',
    updated_at           DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Updated at (DB-controlled; the app never sets this column)',
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'User accounts: credentials, display settings, and role';

-- ---------------------------------------------------------------------
-- refresh_tokens : refresh tokens that keep a login session alive
-- ---------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id         BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'PK (sequential; internal-only, so no UUID needed)',
    user_id    BINARY(16)   NOT NULL COMMENT 'Owning user (foreign key)',
    token_hash VARCHAR(255) NOT NULL COMMENT 'SHA-256 hash of the token; the raw token itself is never stored',
    expires_at DATETIME(6)  NOT NULL COMMENT 'Expiry, computed via the injected Clock (never a no-arg now())',
    created_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Issued at (DB-controlled; the app never sets this column)',
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    -- Prevents the same hash from being inserted twice; also helps catch a
    -- missed revocation during rotation.
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    -- No explicit INDEX on user_id: this FOREIGN KEY makes InnoDB create one
    -- automatically, so lookups by user_id are already covered.
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Refresh tokens; cascade-deleted when the owning user is deleted';

-- ---------------------------------------------------------------------
-- subscriptions : a user's registered foreign-currency subscriptions
-- ---------------------------------------------------------------------
CREATE TABLE subscriptions (
    id                BINARY(16)     NOT NULL COMMENT 'PK (UUID v7, generated by the app)',
    user_id           BINARY(16)     NOT NULL COMMENT 'Owner (foreign key)',
    name              VARCHAR(100)   NOT NULL COMMENT 'Service name (e.g. Netflix)',
    amount            DECIMAL(19, 4) NOT NULL COMMENT 'Billed amount. Always BigDecimal in code to avoid double rounding errors',
    currency          VARCHAR(3)     NOT NULL COMMENT 'Billing currency (ISO 4217)',
    billing_cycle     VARCHAR(10)    NOT NULL COMMENT 'MONTHLY or YEARLY',
    next_payment_date DATE           NOT NULL COMMENT 'Next payment date; read by the detection batch and the roll-forward batch',
    is_active         BOOLEAN        NOT NULL COMMENT 'Notification-eligible flag. false (cancelled) is excluded from the detection batch',
    memo              VARCHAR(500)   NULL     COMMENT 'Free-text memo; the only nullable column in this table',
    created_at        DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Created at (DB-controlled; the app never sets this column)',
    updated_at        DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Updated at (DB-controlled; the app never sets this column)',
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    -- Deliberately excludes is_active: including it would let cancelled
    -- rows with the same name pile up without limit.
    CONSTRAINT uq_subscriptions_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Subscriptions; cascade-deleted when the owning user is deleted';

-- Used by the detection and roll-forward batches; backs the detection
-- query's lower bound (next_payment_date >= :today).
CREATE INDEX idx_subscriptions_active_next_payment
    ON subscriptions (is_active, next_payment_date);

-- ---------------------------------------------------------------------
-- notification_jobs : one row per scheduled notification send
-- ---------------------------------------------------------------------
CREATE TABLE notification_jobs (
    id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'PK. Included in list responses -- the admin retry endpoint takes it as a path variable',
    subscription_id BINARY(16)   NOT NULL COMMENT 'Target subscription (foreign key). Mapped as a real @ManyToOne on the JPA side too',
    user_id         BINARY(16)   NOT NULL COMMENT 'Recipient user (denormalized, filter-only; referential integrity via FK)',
    due_date        DATE         NOT NULL COMMENT 'The payment date this notification is for (snapshotted at job creation)',
    status          VARCHAR(10)  NOT NULL COMMENT 'PENDING / PROCESSING / SENT / FAILED / DEAD / CANCELLED',
    attempt_count   INT          NOT NULL COMMENT 'Attempt count. Normally written by the worker (exceptions: stuck-job recovery, admin retry)',
    -- Never nullable: in SQL, `NULL <= :now` evaluates to NULL, not TRUE, so
    -- such a row would never match the fetch query again.
    next_attempt_at DATETIME(6)  NOT NULL COMMENT 'Earliest time this job may be processed again; used in the single-range fetch condition',
    last_error      VARCHAR(500) NULL     COMMENT 'Summary of the most recent failure or cancellation reason',
    sent_at         DATETIME(6)  NULL     COMMENT 'Time the send succeeded',
    created_at      DATETIME(6)  NOT NULL COMMENT 'Created at (set by the app)',
    updated_at      DATETIME(6)  NOT NULL COMMENT 'Updated at (set by the app)',
    CONSTRAINT pk_notification_jobs PRIMARY KEY (id),
    -- The core of idempotency. The detection batch's
    -- INSERT ... ON DUPLICATE KEY UPDATE relies entirely on this constraint
    -- to prevent duplicate sends -- without it the design does not hold.
    CONSTRAINT uq_notification_jobs_sub_due UNIQUE (subscription_id, due_date),
    CONSTRAINT fk_notification_jobs_subscription FOREIGN KEY (subscription_id)
        REFERENCES subscriptions (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_jobs_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Notification jobs; created by the detection batch and processed by the dispatcher + worker';

-- Backs the dispatcher's fetch condition (status IN (...) AND next_attempt_at <= :now).
CREATE INDEX idx_notification_jobs_status_next_attempt
    ON notification_jobs (status, next_attempt_at);

-- ---------------------------------------------------------------------
-- exchange_rates : daily EUR-based exchange rate snapshot
-- ---------------------------------------------------------------------
CREATE TABLE exchange_rates (
    id             BIGINT         NOT NULL AUTO_INCREMENT COMMENT 'PK',
    base_currency  VARCHAR(3)     NOT NULL COMMENT 'Base currency; always EUR (Frankfurter API convention)',
    quote_currency VARCHAR(3)     NOT NULL COMMENT 'Quote currency (ISO 4217)',
    rate           DECIMAL(19, 8) NOT NULL COMMENT '1 base = rate quote. Scale 8 -- scale 4 (same as amounts) is not precise enough',
    rate_date      DATE           NOT NULL COMMENT 'Publication date returned by the external API (ECB-based). Staying on Friday over a weekend is expected',
    fetched_at     DATETIME(6)    NOT NULL COMMENT 'When this row was actually fetched from the external API; do not confuse with rate_date',
    CONSTRAINT pk_exchange_rates PRIMARY KEY (id),
    -- Makes re-running the fetch batch (UPSERT) safe.
    CONSTRAINT uq_exchange_rates UNIQUE (base_currency, quote_currency, rate_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
  COMMENT = 'Daily exchange-rate cache; the app keeps running on the latest cached values if the external API is down';

-- Backs findFirstByOrderByRateDateDesc, which fetches the latest rate_date.
CREATE INDEX idx_exchange_rates_rate_date
    ON exchange_rates (rate_date);
